"use client";
import { useEffect, useState } from "react";

type Place = { name: string; summary: string; now: string; high: number; low: number; hourly: string[][]; days?: string[][] };
const fallbackPlaces: Place[] = [
  { name: "埼玉県川口市", summary: "晴れ時々くもり", now: "28°", high: 32, low: 24, hourly: [["いま","☀️","28°","0mm"],["13時","🌤️","30°","0mm"],["14時","🌤️","31°","0mm"],["15時","☀️","32°","0mm"],["16時","🌤️","31°","0mm"],["17時","☁️","30°","0mm"],["18時","☁️","29°","0mm"],["19時","☁️","28°","0mm"],["20時","☁️","27°","0mm"],["21時","🌙","27°","0mm"],["22時","🌙","26°","0mm"],["23時","🌙","26°","0mm"]] },
  { name: "東京都台東区", summary: "晴れのちくもり", now: "27°", high: 31, low: 25, hourly: [["いま","☀️","27°","0mm"],["13時","☀️","29°","0mm"],["14時","🌤️","30°","0mm"],["15時","🌤️","31°","0mm"],["16時","🌤️","31°","0mm"],["17時","☁️","30°","0mm"],["18時","☁️","29°","0mm"],["19時","☁️","28°","0mm"],["20時","☁️","27°","0mm"],["21時","🌙","27°","0mm"],["22時","🌙","26°","0mm"],["23時","🌙","26°","0mm"]] }
];
const days = [["今日","☀️","32°","24°","10%"],["明日","🌤️","33°","25°","20%"],["明後日","🌦️","31°","25°","50%"],["3日後","🌤️","32°","24°","20%"]];
const incidents = [["JR宇都宮線","遅延","一部列車に遅れが出ています"],["東京メトロ東西線","直通運転中止","JR線との直通運転を中止しています"]];
type Tab = "hourly" | "today" | "days";
export default function Home() {
 const [tab,setTab]=useState<Tab>("hourly"),[dark,setDark]=useState(false),[updating,setUpdating]=useState(false),[updated,setUpdated]=useState(""),[places,setPlaces]=useState<Place[]>(fallbackPlaces);
 const updateWeather=async()=>{const response=await fetch("/api/weather");if(!response.ok)throw new Error("weather");const data=await response.json() as {places:Place[];fetchedAt:string};setPlaces(data.places);setUpdated(new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(data.fetchedAt)))};
 useEffect(()=>{const next=()=>setUpdated(new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date()));next();updateWeather().catch(()=>{});const saved=localStorage.getItem("theme");setDark(saved? saved==="dark":matchMedia("(prefers-color-scheme:dark)").matches)},[]);
 useEffect(()=>{document.documentElement.dataset.theme=dark?"dark":"light";localStorage.setItem("theme",dark?"dark":"light")},[dark]);
 const refresh=async()=>{setUpdating(true);try{await updateWeather()}catch{setUpdated("取得に失敗しました")}finally{setUpdating(false)}};
 return <main><header className="bar wrap"><a className="brand" href="#top"><b>☀</b>首都圏 <strong>天気・運行情報</strong></a><div className="actions"><small><i/> 最終更新 {updated||"読込中"}</small><button className="refresh" disabled={updating} onClick={refresh}>↻ {updating?"更新中…":"情報を更新"}</button><button onClick={()=>setDark(!dark)}>{dark?"☀ ライト":"☾ ダーク"}</button></div></header>
 <section id="top" className="hero wrap"><div><p>WEATHER & TRANSIT / TOKYO AREA</p><h1>今日の空模様と、<br/><em>いつもの移動</em>をひと目で。</h1><span>川口市・台東区の天気と、首都圏の気になる運行情報をまとめてお届けします。</span></div><aside><b>☀️</b><div><small>きょうの東京エリア</small><strong>夏空、広がる。</strong><span>最高 32° / 最低 24°</span></div></aside></section>
 <section className="weather wrap"><div className="title"><div><p>WEATHER FORECAST</p><h2>2地域の天気予報</h2></div><small>気象データ取得日時：{updated}</small></div><nav>{([['hourly','1時間ごと'],['today','今日・明日'],['days','今日〜3日後']] as const).map(([k,t])=><button className={tab===k?'active':''} onClick={()=>setTab(k)} key={k}>{t}</button>)}</nav><div className="cards">{places.map(place=><article key={place.name}><div className="cardhead"><div><small>{place.name}</small><h3>{place.summary}</h3></div><b>☀️</b></div>{tab==='hourly'&&<div className="hourly">{place.hourly.map(x=><div key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><strong>{x[2]}</strong><span>☔ {x[3]}</span></div>)}</div>}{tab==='today'&&<div className="today"><div>最高 <b>{place.high}°</b><br/>最低 <i>{place.low}°</i></div><div><small>降水確率</small><p>午前　<strong>10%</strong></p><p>午後　<strong>20%</strong></p></div></div>}{tab==='days'&&<div className="days">{days.map(d=><div key={d[0]}><small>{d[0]}</small><b>{d[1]}</b><strong>{d[2]} <i>{d[3]}</i></strong><span>☔ {d[4]}</span></div>)}</div>}</article>)}</div></section>
 <section className="transit wrap"><div className="transithead"><div><p>TRAIN STATUS</p><h2>首都圏の運行情報</h2><span>東京・埼玉・栃木のJR線、東京メトロ全線から、遅延・事故などがある路線のみを表示しています。</span></div><aside><b>!</b><strong>2</strong><small>路線でお知らせ</small></aside></div><div className="list">{incidents.map(x=><div key={x[0]}><i/><p><b>{x[0]}</b><span>{x[2]}</span></p><em>{x[1]}</em></div>)}</div><small>運行情報取得日時：{updated}　情報提供：公共交通オープンデータセンター（接続設定後に反映予定）</small></section><footer className="wrap">首都圏 天気・運行情報 <span>表示時刻は日本時間（JST）です</span></footer></main>
}
